<?php

/**
 * @file
 * Provides custom peertube provider.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function peertube_media_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the peertube module.
    case 'help.page.peertube_media_migration': 
      $output = '';
      $output .= '<h3>' . t('peertube media migration') . '</h3>';
      $output .= '<p>' . t('This module fetches Peertube captions and thumbnails as media for remote media oembed links.') . '</p>';
      return $output;

    default:
  }
}
