custom_peertube_migration.settings:
  type: config_object
  label: 'Peertube Video Migration settings'
  mapping:
    base_uri:
      type: string
      label: 'Peertube API Endpoint'
      constraints:
        NotBlank:
          message: "Please set Peertube API uri."
